# Generated by Django 3.2.5 on 2022-01-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tender_model',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('opning_date', models.DateField()),
                ('organisation_chain', models.CharField(max_length=500)),
                ('tender_title', models.CharField(max_length=1000)),
                ('ref_no', models.CharField(max_length=100)),
                ('tender_id', models.CharField(max_length=100)),
                ('tender_url', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'tender_model',
            },
        ),
    ]
